In [ ]:
#Question1


In [2]:
import numpy as np

In [3]:
arry1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
mat = arry1.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#Question2


In [7]:
arry2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arry2[arry2%2!=0]=-1

In [9]:
print(arry2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [10]:
#Question3


In [12]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

In [13]:
greater_than = np.where(x>y)[0]
equals = np.where(x==y)[0]

In [18]:
print(greater_than, end=', ')
print(equals)

[1 2 4 5 6 7 8 9], [0]


In [ ]:
#Question4


In [15]:
arry4 = np.arange(100).reshape(5,-1)

In [16]:
arry4


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [17]:
first_four_columns = arry4[:, :4]
print(first_four_columns)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [19]:
#AD-1


In [20]:
random_array = np.random.randint(30, 41, size=10)
print(random_array)

[31 34 39 39 34 35 40 33 34 36]


In [21]:
#AD-2


In [24]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
B = np.array([[7, 8, 10], [4, 5, 6], [1, 2, 3]])

In [27]:
C = A + B
E = A - B
print(C)
print(E)


[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [30]:
sum_A = np.sum(A)
sum_columns_B = np.sum(B, axis=0)
sum_rows_C = np.sum(C, axis=1)
D = np.dot(A, B)
E_sorted = np.sort(C, axis=None).reshape(C.shape)
E_transposed = np.transpose(E_sorted)

In [31]:
print("\nSum of all elements of Matrix A:")
print(sum_A)
print("\nSum of each column of Matrix B:")
print(sum_columns_B)
print("\nSum of each row of Matrix C:")
print(sum_rows_C)

print("\nMatrix D (A * B):")
print(D)
print(E_sorted)
print(E_transposed)


Sum of all elements of Matrix A:
46

Sum of each column of Matrix B:
[12 15 19]

Sum of each row of Matrix C:
[31 30 31]

Matrix D (A * B):
[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]
[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
