In [1]:
import torch

In [8]:
import torch


tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

reshaped_tensor = tensor.reshape(3, 2)
print(reshaped_tensor)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [9]:
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

stacked_tensor = torch.stack((tensor1, tensor2), dim=0)
print(stacked_tensor)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [15]:

tensor = torch.tensor([[[[1, 2]], [[3, 4]], [[5, 6]]]])


squeezed_tensor = tensor.squeeze()
print(squeezed_tensor)
print(squeezed_tensor.shape)  


tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [16]:
tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])

unsqueezed_tensor = tensor.unsqueeze(0)
print(unsqueezed_tensor.shape)  

torch.Size([1, 3, 2])


In [17]:
#q2

tensor = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                      [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

In [18]:

permuted_tensor = tensor.permute(2, 0, 1)  # New order of dimensions (4, 2, 3)

print("\nPermuted tensor shape:", permuted_tensor.shape)
print("Permuted tensor:")
print(permuted_tensor)


Permuted tensor shape: torch.Size([4, 2, 3])
Permuted tensor:
tensor([[[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]],

        [[ 4,  8, 12],
         [16, 20, 24]]])


In [20]:
#q3

tensor = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

print("Original tensor:")
print(tensor)


print("\nElement at (0, 2):", tensor[0, 2])  


print("Element at (2, 1):", tensor[2, 1]) 


Original tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Element at (0, 2): tensor(3)
Element at (2, 1): tensor(10)


In [22]:
#q4
import numpy as np

numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

tensor = torch.tensor(numpy_array)

print("NumPy Array:")
print(numpy_array)
print("\nConverted PyTorch Tensor:")
print(tensor)

NumPy Array:
[[1 2 3]
 [4 5 6]]

Converted PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [23]:

converted_numpy_array = tensor.numpy()

print("\nConverted back to NumPy Array:")
print(converted_numpy_array)



Converted back to NumPy Array:
[[1 2 3]
 [4 5 6]]


In [24]:
#q5
random_tensor = torch.rand(7, 7)

print(random_tensor)

tensor([[6.8229e-01, 5.9991e-01, 2.4928e-01, 3.1391e-01, 7.9773e-01, 6.5766e-02,
         3.5743e-01],
        [8.6184e-01, 1.0489e-01, 6.4127e-01, 6.1665e-01, 5.5711e-01, 6.1080e-01,
         2.3498e-01],
        [4.5348e-01, 1.9939e-01, 5.3917e-01, 2.9446e-01, 5.1866e-01, 4.3579e-01,
         5.1640e-01],
        [3.8133e-01, 9.0318e-01, 1.5636e-01, 4.3153e-02, 1.8840e-01, 3.0273e-02,
         8.5969e-01],
        [6.7783e-01, 6.1948e-01, 6.4274e-01, 8.7747e-01, 8.0782e-04, 1.6470e-01,
         9.2180e-01],
        [5.5812e-01, 8.0828e-01, 3.6762e-01, 3.5456e-01, 8.1281e-01, 6.0791e-02,
         2.2263e-01],
        [3.0678e-01, 2.6425e-02, 6.8061e-01, 2.9340e-01, 9.9727e-01, 9.1092e-01,
         8.9383e-01]])


In [34]:
#q6

given_tensor = torch.rand(2, 7)
random_tensor = torch.rand(1, 7)
result_tensor = given_tensor * random_tensor

print("Given Tensor (2, 7):")
print(given_tensor)
print("\nRandom Tensor (1, 7):")
print(random_tensor)
print("\nResult of Element-wise Multiplication:")
print(result_tensor)

Given Tensor (2, 7):
tensor([[0.5481, 0.4406, 0.1086, 0.7525, 0.6797, 0.3918, 0.5174],
        [0.7650, 0.9777, 0.9185, 0.6510, 0.1338, 0.3980, 0.7673]])

Random Tensor (1, 7):
tensor([[0.4146, 0.9097, 0.0088, 0.2581, 0.5355, 0.3094, 0.4316]])

Result of Element-wise Multiplication:
tensor([[0.2272, 0.4008, 0.0010, 0.1942, 0.3640, 0.1212, 0.2233],
        [0.3171, 0.8894, 0.0081, 0.1681, 0.0717, 0.1232, 0.3312]])


In [42]:
#q7
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

print("Tensor 1 ", tensor1)
print("Tensor 2 ", tensor2)

cpu
Tensor 1  tensor([[0.2156, 0.9485, 0.4880],
        [0.6567, 0.0781, 0.4553]])
Tensor 2  tensor([[0.3846, 0.4716, 0.0318],
        [0.9560, 0.5439, 0.5773]])


In [39]:
#q8

random_tensor_transposed = random_tensor.T  
result_matrix = torch.mm(given_tensor, random_tensor_transposed)
print("Given Tensor (2, 7):")
print(given_tensor)
print("\nRandom Tensor (1, 7):")
print(random_tensor)
print("\nResult of Matrix Multiplication (2, 1):")
print(result_matrix)


Given Tensor (2, 7):
tensor([[0.5481, 0.4406, 0.1086, 0.7525, 0.6797, 0.3918, 0.5174],
        [0.7650, 0.9777, 0.9185, 0.6510, 0.1338, 0.3980, 0.7673]])

Random Tensor (1, 7):
tensor([[0.4146, 0.9097, 0.0088, 0.2581, 0.5355, 0.3094, 0.4316]])

Result of Matrix Multiplication (2, 1):
tensor([[1.5318],
        [1.9087]])


In [40]:
#q9
max_tensor1, min_tensor1 = tensor1.max(), tensor1.min()
max_tensor2, min_tensor2 = tensor2.max(), tensor2.min()
print(max_tensor1,max_tensor2)
print(min_tensor1,min_tensor2)

tensor(0.8025) tensor(0.9923)
tensor(0.0086) tensor(0.1560)


In [41]:
#q10


max_val_tensor1, max_idx_tensor1 = tensor1.max(dim=1)
min_val_tensor1, min_idx_tensor1 = tensor1.min(dim=1)
max_val_tensor2, max_idx_tensor2 = tensor2.max(dim=1)
min_val_tensor2, min_idx_tensor2 = tensor2.min(dim=1)


print("Tensor 1:")
print(tensor1)
print(f"Max value indices for tensor1: {max_idx_tensor1}")
print(f"Min value indices for tensor1: {min_idx_tensor1}\n")
print("Tensor 2:")
print(tensor2)
print(f"Max value indices for tensor2: {max_idx_tensor2}")
print(f"Min value indices for tensor2: {min_idx_tensor2}")

Tensor 1:
tensor([[0.8025, 0.1424, 0.0086],
        [0.1720, 0.5594, 0.3486]])
Max value indices for tensor1: tensor([0, 1])
Min value indices for tensor1: tensor([2, 0])

Tensor 2:
tensor([[0.4190, 0.9923, 0.6818],
        [0.2315, 0.1560, 0.3999]])
Max value indices for tensor2: tensor([1, 2])
Min value indices for tensor2: tensor([0, 1])
